### ISSUE TITLE
task_python_vta.py failed

### ISSUE THREAD

**Issue by wweic** [neo-ai/tvm#9]
https://neo-ai-ci.amazon-ml.com/blue/organizations/jenkins/tvm/detail/PR-7/7/pipeline/36

```
+ docker/bash.sh tvmai/ci-cpu ./tests/scripts/task_python_vta.sh

WORKSPACE: /home/ubuntu/workspace/tvm/build-cpu

DOCKER CONTAINER NAME: tvmai/ci-cpu



Running './tests/scripts/task_python_vta.sh' inside tvmai/ci-cpu...

docker

mesg: ttyname failed: Inappropriate ioctl for device

Adding group `ubuntu' (GID 1000) ...

Done.

cd python; python setup.py build_ext --inplace

/usr/local/lib/python2.7/dist-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /workspace/python/tvm/_ffi/_cython/core.pyx

  tree = Parsing.p_module(s, pxd, full_module_name)

Compiling tvm/_ffi/_cython/core.pyx because it changed.

[1/1] Cythonizing tvm/_ffi/_cython/core.pyx

/usr/lib/python2.7/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.5.dev' to '0.5.dev0'

  normalized_version,

running build_ext

building 'tvm._ffi._cy2.core' extension

creating build

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/tvm

creating build/temp.linux-x86_64-2.7/tvm/_ffi

creating build/temp.linux-x86_64-2.7/tvm/_ffi/_cython

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I../include/ -I../3rdparty/dmlc-core/include -I../3rdparty/dlpack/include -I/usr/include/python2.7 -c tvm/_ffi/_cython/core.cpp -o build/temp.linux-x86_64-2.7/tvm/_ffi/_cython/core.o

cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/tvm

creating build/lib.linux-x86_64-2.7/tvm/_ffi

creating build/lib.linux-x86_64-2.7/tvm/_ffi/_cy2

c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/tvm/_ffi/_cython/core.o -o build/lib.linux-x86_64-2.7/tvm/_ffi/_cy2/core.so

copying build/lib.linux-x86_64-2.7/tvm/_ffi/_cy2/core.so -> tvm/_ffi/_cy2

cd python; python3 setup.py build_ext --inplace

running build_ext

building 'tvm._ffi._cy3.core' extension

creating build/temp.linux-x86_64-3.6

creating build/temp.linux-x86_64-3.6/tvm

creating build/temp.linux-x86_64-3.6/tvm/_ffi

creating build/temp.linux-x86_64-3.6/tvm/_ffi/_cython

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I../include/ -I../3rdparty/dmlc-core/include -I../3rdparty/dlpack/include -I/usr/include/python3.6m -c tvm/_ffi/_cython/core.cpp -o build/temp.linux-x86_64-3.6/tvm/_ffi/_cython/core.o

cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++

creating build/lib.linux-x86_64-3.6

creating build/lib.linux-x86_64-3.6/tvm

creating build/lib.linux-x86_64-3.6/tvm/_ffi

creating build/lib.linux-x86_64-3.6/tvm/_ffi/_cy3

x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/tvm/_ffi/_cython/core.o -o build/lib.linux-x86_64-3.6/tvm/_ffi/_cy3/core.cpython-36m-x86_64-linux-gnu.so

copying build/lib.linux-x86_64-3.6/tvm/_ffi/_cy3/core.cpython-36m-x86_64-linux-gnu.so -> tvm/_ffi/_cy3

/usr/local/lib/python3.6/dist-packages/setuptools/dist.py:398: UserWarning: Normalizing '0.5.dev' to '0.5.dev0'

  normalized_version,

Running unittest...

Failure: NameError (name 'avg_pool2d_alter_layout' is not defined) ... ERROR

Failure: ImportError (cannot import name cpp) ... ERROR



======================================================================

ERROR: Failure: NameError (name 'avg_pool2d_alter_layout' is not defined)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName

    addr.filename, addr.module)

  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath

    return self.importFromDir(dir_path, fqname)

  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir

    mod = load_module(part_fqname, fh, filename, desc)

  File "/workspace/vta/tests/python/unittest/test_environment.py", line 1, in <module>

    import vta

  File "/workspace/vta/python/vta/__init__.py", line 20, in <module>

    from . import top

  File "/workspace/vta/python/vta/top/__init__.py", line 3, in <module>

    from .vta_conv2d import packed_conv2d, schedule_packed_conv2d

  File "/workspace/vta/python/vta/top/vta_conv2d.py", line 8, in <module>

    import topi

  File "/workspace/topi/python/topi/__init__.py", line 26, in <module>

    from . import cuda

  File "/workspace/topi/python/topi/cuda/__init__.py", line 14, in <module>

    from .pooling import schedule_pool, schedule_global_pool

  File "/workspace/topi/python/topi/cuda/pooling.py", line 136, in <module>

    @avg_pool2d_alter_layout.register(["cuda"])

NameError: name 'avg_pool2d_alter_layout' is not defined



======================================================================

ERROR: Failure: ImportError (cannot import name cpp)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName

    addr.filename, addr.module)

  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath

    return self.importFromDir(dir_path, fqname)

  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir

    mod = load_module(part_fqname, fh, filename, desc)

  File "/workspace/vta/tests/python/unittest/test_vta_insn.py", line 4, in <module>

    import topi

  File "/workspace/topi/python/topi/__init__.py", line 16, in <module>

    from . import cpp

ImportError: cannot import name cpp



----------------------------------------------------------------------

Ran 2 tests in 0.237s



FAILED (errors=2)

Terminated

script returned exit code 255
```

**Comment by hcho3** [comment]
We may need to create an AMI from scratch to ensure that all TVM build steps can finish successfully.

**Comment by wweic** [comment]
Fixed in latest `dev` branch.
